### ISSUE TITLE
Request for internationalization of some strings

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-typedoc-theme#2]
Logging the strings in the Typedoc and SSAS doc which need localization in the future:

https://jp.infragistics.com/angular-docs/typescript/
All
Inherited
Externals
Enumerations
Classes
Interfaces
Variables
Functions
Object literals
Search API (that's the search box text in the upper left corner below the IgniteUI for Angular header)

Public
Public/Protected - these three strings are displayed when you hover over the "All" strings in the upper left corner (below the "Search API..." search box)
All

GLOBALS - string in the TOC on the left side of the page
Variables (second instanced of this sting)
Functions (second instanced of this sting)
Object literals (second instanced of this sting)

https://jp.infragistics.com/products/ignite-ui-angular/docs/sass/
Search API... - text of the search box in the upper left corner

**Comment by Aleksandyr** [comment]
@valadzhov In order to close this issue we need to do the following:
1. Localize and merge the newly exposed strings from this pr [here](https://github.com/IgniteUI/igniteui-angular/pull/5907).
2. Merge the [PR ](https://github.com/IgniteUI/igniteui-typedoc-theme/pull/3) that has been made here.
3. Run and test all of the strings with the [enhancement](https://github.com/IgniteUI/typedoc-plugin-localization/pull/41) in the typedoc plugin.
